# Generated by Django 4.1 on 2022-08-08 23:15

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_students_student_rename_subjects_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_id',
            field=models.CharField(default=accounts.utils.generate_school_id, editable=False, max_length=100),
        ),
    ]
