# Generated by Django 4.1 on 2022-09-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current_session',
            field=models.BooleanField(default=False),
        ),
    ]
