# Generated by Django 4.1 on 2022-09-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_session_current_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentSession',
        ),
    ]
