# Generated by Django 4.1 on 2022-09-12 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_currentsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment', models.CharField(choices=[(1, 'assignment'), (2, 'test'), (3, 'examination'), (4, 'project')], default=1, max_length=120)),
                ('mark', models.FloatField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentResult',
        ),
    ]
