# Generated by Django 4.1 on 2022-09-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentassessment_assessment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
