# Generated by Django 4.1 on 2022-09-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_student_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentassessment',
            old_name='assessment',
            new_name='assessment_type',
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
