# Generated by Django 4.1 on 2022-09-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_assessment_studentassessment_assessment_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentassessment',
            old_name='mark',
            new_name='score',
        ),
    ]
