# Generated by Django 4.1 on 2022-09-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_mark_studentassessment_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentassessment',
            old_name='assessment_name',
            new_name='assessment_desc',
        ),
    ]
