# Generated by Django 4.1 on 2022-10-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_assessment_name_studentassessment_assessment_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassessment',
            name='assessment_type',
            field=models.CharField(choices=[('assignment', 'assignment'), ('test', 'test'), ('examination', 'examination'), ('project', 'project')], default=1, max_length=120),
        ),
    ]
