# Generated by Django 4.1 on 2022-10-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_payment_session_alter_fee_fee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isOld',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='session_completed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
