# Generated by Django 4.1 on 2022-08-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_id',
            field=models.CharField(default='kdjf', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
