# Generated by Django 4.1 on 2022-10-21 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_student_isold_student_session_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.classlevel'),
        ),
    ]
