# Generated by Django 4.1 on 2022-10-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_student_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.PositiveIntegerField(choices=[(1, 'Ongoing'), (2, 'Graduated'), (3, 'Left')], default=1),
        ),
    ]
