# Generated by Django 4.1 on 2022-08-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_school_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
