# Generated by Django 4.1 on 2022-10-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_term_studentassessment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='previous_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
