# Generated by Django 4.1 on 2022-11-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_student_previous_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='current_term',
            field=models.BooleanField(default=False),
        ),
    ]
