# Generated by Django 4.1 on 2022-08-17 20:00

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='school_id',
            field=models.CharField(default=accounts.utils.generate_school_id, editable=False, max_length=100, unique=True),
        ),
    ]
