# Generated by Django 4.1 on 2022-11-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_student_term_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.session'),
        ),
    ]
