# Generated by Django 4.1 on 2022-11-17 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_student_current_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessment',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.classlevel'),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.session'),
        ),
        migrations.AlterField(
            model_name='studentassessment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.term'),
        ),
    ]
