# Generated by Django 4.1 on 2022-11-18 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_studentassessment_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='previous_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='previous_class', to='accounts.classlevel'),
        ),
    ]
