# Generated by Django 4.1 on 2022-11-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_student_previous_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='isOld',
            new_name='is_old',
        ),
    ]
