# Generated by Django 4.1 on 2022-08-06 20:41

from django.db import migrations, models
import django.db.models.deletion
import management_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(1, 'Administrator'), (2, 'Staff'), (3, 'Student')], default=1)),
                ('school_id', models.CharField(default=management_app.models.generate_pk, editable=False, max_length=10)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('other_names', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_numbers', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management_app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management_app.classlevel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management_app.classlevel')),
                ('school_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.schoolsession')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management_app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management_app.customuser')),
            ],
        ),
    ]
